export const CREATE_BALLOON = 'CREATE_BALLOON';
export const FETCH_BALLOON = 'FETCH_BALLOON';
export const FETCH_BALLOONS = 'FETCH_BALLOONS';
export const EDIT_BALLOON = 'EDIT_BALLOON';
export const DELETE_BALLOON = 'DELETE_BALLOON';
export const UPDATE_BALLOON = 'UPDATE_BALLOON';

export const CREATE_CAMPAIGN = 'CREATE_CAMPAIGN';
export const FETCH_CAMPAIGN = 'FETCH_CAMPAIGN';
export const FETCH_CAMPAIGNS = 'FETCH_CAMPAIGNS';
export const EDIT_CAMPAIGN = 'EDIT_CAMPAIGN';
export const DELETE_CAMPAIGN = 'DELETE_CAMPAIGN';
export const UPDATE_CAMPAIGN = 'UPDATE_CAMPAIGN';
